### ISSUE TITLE
[WinError 2] 系統找不到指定的檔案。

### ISSUE THREAD

**Issue by Doge55** [hcjohn463/JableTVDownload#10]
我是影片有成功下載下來
但當開始合成影片時
會出現下列代碼
Traceback (most recent call last):
  File "main.py", line 131, in <module>
    encodeMp4(folderPath)
  File "C:\Users\test\Downloads\JableTVDownload-main\encode.py", line 21, in encodeMp4
    .output(needFile, **output_args)
  File "C:\Users\test\AppData\Local\Programs\Python\Python36\lib\site-packages\ffmpeg\_run.py", line 320, in run
    overwrite_output=overwrite_output,
  File "C:\Users\test\AppData\Local\Programs\Python\Python36\lib\site-packages\ffmpeg\_run.py", line 285, in run_async
    args, stdin=stdin_stream, stdout=stdout_stream, stderr=stderr_stream
  File "C:\Users\test\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\Users\test\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系統找不到指定的檔案。
不知是哪個步驟錯了?

**Comment by hcjohn463** [comment]
這是因為你沒有安裝FFMPEG哦 系統沒讀到

**Comment by Doge55** [comment]
FFMPEG有要指定放在哪裡嗎
我有安裝並放在C:\ffmpeg

**Comment by hcjohn463** [comment]
> FFMPEG有要指定放在哪裡嗎
> 我有安裝並放在C:\ffmpeg

在command line 輸入ffmpeg 有成功跑出回傳的東西嗎?
如果有的話我再想想辦法

**Comment by Doge55** [comment]
有噢
ffmpeg version 4.4-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
辛苦啦~

**Comment by hcjohn463** [comment]
> 有噢
> ffmpeg version 4.4-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
> built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
> configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
> libavutil 56. 70.100 / 56. 70.100
> libavcodec 58.134.100 / 58.134.100
> libavformat 58. 76.100 / 58. 76.100
> libavdevice 58. 13.100 / 58. 13.100
> libavfilter 7.110.100 / 7.110.100
> libswscale 5. 9.100 / 5. 9.100
> libswresample 3. 9.100 / 3. 9.100
> libpostproc 55. 9.100 / 55. 9.100
> Hyper fast Audio and Video encoder
> usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
> 
> Use -h to get full help or, even better, run 'man ffmpeg'
> 辛苦啦~

您好，已經更新過了 再請您幫忙測試看看能不能
感激不盡~

**Comment by Doge55** [comment]
成功了! 太神啦
感謝大大造福人群

**Comment by Doge55** [comment]
Traceback (most recent call last):
  File "main.py", line 117, in <module>
    mergeMp4(folderPath, tsList)
  File "C:\Users\users\Downloads\JableTVDownload-main\merge.py", line 14, in mergeMp4
    with open(os.path.join(folderPath, video_name + '.mp4'), 'ab') as f2:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\users\\Downloads\\JableTVDownload-main\\ssis-097\\ssis-097.mp4'
想在請問一下這樣是遇到什麼問題

**Comment by hcjohn463** [comment]
已更新重新上傳!
如果覺得好用 再麻煩你們幫忙按個星星
這樣搜尋才能到比較上面
有問題提出我都會繼續更新
大家一起讓世界更美好
謝謝你們~
