### ISSUE TITLE
dr = webdriver.Chrome(chrome_options=options) 錯誤問題

### ISSUE THREAD

**Issue by kylechan921** [hcjohn463/JableTVDownload#101]
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    download(url)
  File "/volume1/homes/nasadmin/JableTVDownload/download.py", line 38, in download
    dr = webdriver.Chrome(chrome_options=options)
  File "/var/services/homes/nasadmin/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 84, in __init__
    super().__init__(
  File "/var/services/homes/nasadmin/.local/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 101, in __init__
    self.service.start()
  File "/var/services/homes/nasadmin/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 100, in start
    self.assert_process_still_running()
  File "/var/services/homes/nasadmin/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 113, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /var/services/homes/nasadmin/.cache/selenium/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127

**Comment by Road-tech** [comment]
不妨试试docker  https://github.com/Road-tech/Docker_JableTVDownload
