### ISSUE TITLE
URLLIB  ERROR:HTTP ERROR 428.

### ISSUE THREAD

**Issue by 1563726608** [hcjohn463/JableTVDownload#102]
DevTools listening on ws://127.0.0.1:54496/devtools/browser/23b59684-c0ff-437a-b6ab-281edcb07bdf
[0516/171602.913:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[0516/171606.190:INFO:CONSOLE(465)] "An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.", source: https://imasdk.googleapis.com/js/sdkloader/ima3.js (465)
[0516/171606.199:INFO:CONSOLE(0)] "An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.", source: about:srcdoc (0)
[0516/171606.370:INFO:CONSOLE(0)] "Access to XMLHttpRequest at 'https://ao-block-ater.mushroomtrack.com/bcdn_token=d6CCUMif4eXwH5tm5XG0ioOjhYxJn44Gdsad237Vv_Q&expires=1684235763&token_path=%2Fvod%2F/vod/8000/8803/8803.m3u8' from origin 'https://jable.tv' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.", source: https://jable.tv/videos/salo-017/ (0)
[0516/171607.605:INFO:CONSOLE(0)] "Access to XMLHttpRequest at 'https://ao-block-ater.mushroomtrack.com/bcdn_token=d6CCUMif4eXwH5tm5XG0ioOjhYxJn44Gdsad237Vv_Q&expires=1684235763&token_path=%2Fvod%2F/vod/8000/8803/8803.m3u8' from origin 'https://jable.tv' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.", source: https://jable.tv/videos/salo-017/ (0)
[0516/171607.642:INFO:CONSOLE(0)] "Uncaught (in promise) undefined", source: https://jable.tv/videos/salo-017/ (0)
result: <re.Match object; span=(52100, 52258), match='https://ao-block-ater.mushroomtrack.com/bcdn_toke>
m3u8url: https://ao-block-ater.mushroomtrack.com/bcdn_token=d6CCUMif4eXwH5tm5XG0ioOjhYxJn44Gdsad237Vv_Q&expires=1684235763&token_path=%2Fvod%2F/vod/8000/8803/8803.m3u8
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    download(url)
  File "D:\SoftWare\jabletvdownload\download.py", line 60, in download
    urllib.request.urlretrieve(m3u8url, m3u8file)
  File "D:\SoftWare\Python\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "D:\SoftWare\Python\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "D:\SoftWare\Python\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "D:\SoftWare\Python\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "D:\SoftWare\Python\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "D:\SoftWare\Python\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "D:\SoftWare\Python\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 428:

**Comment by Dissyu** [comment]
也遇到了 ........
