### ISSUE TITLE
http.client.RemoteDisconnected: Remote end closed connection without response 下载失败

### ISSUE THREAD

**Issue by joywqy** [hcjohn463/JableTVDownload#103]
求解，谢谢

**Comment by joywqy** [comment]
```python
C:\Users\wqy\Desktop\JableTVDownload-main>python main.py --url https://jable.tv/videos/081319-002/
要轉檔嗎?(y/n)y
要用GPU(Nvidia)加速轉檔嗎?(y/n)y
正在下載影片: https://jable.tv/videos/081319-002/
Traceback (most recent call last):
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\urllib3\connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\http\client.py", line 1377, in getresponse
    response.begin()
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\http\client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\http\client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in __init__
    super().__init__(
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\urllib3\_request_methods.py", line 118, in request
    return self.request_encode_body(
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\urllib3\_request_methods.py", line 217, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\urllib3\poolmanager.py", line 433, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\urllib3\connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\http\client.py", line 1377, in getresponse
    response.begin()
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\http\client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\http\client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wqy\Desktop\JableTVDownload-main\main.py", line 14, in <module>
    download(url)
  File "C:\Users\wqy\Desktop\JableTVDownload-main\download.py", line 46, in download
    dr = webdriver.Chrome(chrome_options=options)
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 84, in __init__
    super().__init__(
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 115, in __init__
    self.quit()
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 242, in quit
    self.service.stop()
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\selenium\webdriver\common\service.py", line 145, in stop
    self.send_remote_shutdown_command()
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\selenium\webdriver\common\service.py", line 124, in send_remote_shutdown_command
    request.urlopen(f"{self.service_url}/shutdown")
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\urllib\request.py", line 1375, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\urllib\request.py", line 1350, in do_open
    r = h.getresponse()
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\http\client.py", line 1377, in getresponse
    response.begin()
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\http\client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\http\client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
``` 
网上搜索了下这个错误，说是要指定User-Agent就行了 ？

**Comment by Dissyu** [comment]
請問有解嗎

**Comment by joywqy** [comment]
> 



> 請問有解嗎

Mei
