### ISSUE TITLE
能否添加Edge瀏覽器支持，ChromeDriver還得安裝Chrome瀏覽器

### ISSUE THREAD

**Issue by fujiwara-takumi** [hcjohn463/JableTVDownload#106]
能否添加Edge瀏覽器支持，ChromeDriver還得安裝Chrome瀏覽器

**Comment by cocoshenFang** [comment]
先去下載適合的 Edgedriver
https://developer.microsoft.com/zh-tw/microsoft-edge/tools/webdriver/

download.py 修改為以下
  options = webdriver.EdgeOptions()
  options.add_argument('--no-sandbox')
  options.add_argument('--disable-dev-shm-usage')
  options.add_argument('--disable-extensions')
  options.add_argument('--headless')
  options.add_argument("user-agent=Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36 Edge/18.18363")
  dr = webdriver.Edge(options=options)

**Comment by anonymous-whac** [comment]
(jable) D:\Python Script\JableTVDownload>python main.py
Traceback (most recent call last):
  File "D:\Python Script\JableTVDownload\main.py", line 5, in <module>
    from download import download
  File "D:\Python Script\JableTVDownload\download.py", line 40
    options = webdriver.EdgeOptions()
IndentationError: unexpected indent

**Comment by chenrujun-ROC** [comment]
@anonymous-whac 縮排有問題
