### ISSUE TITLE
download failed

### ISSUE THREAD

**Issue by luhuimao** [hcjohn463/JableTVDownload#118]
[0713/220615.448:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    download(url)
  File "I:\github\JableTVDownload\download.py", line 47, in download
    dr.get(url)
  File "I:\github\JableTVDownload\jable\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "I:\github\JableTVDownload\jable\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "I:\github\JableTVDownload\jable\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT
  (Session info: headless chrome=114.0.5735.199)

**Comment by kptung** [comment]
chrome+chreome_driver版本不合
