### ISSUE TITLE
这个问题怎么解决，我被网站屏蔽了吗？不知道是什么意思，

### ISSUE THREAD

**Issue by yinhaoooo** [hcjohn463/JableTVDownload#12]
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    urllib.request.urlretrieve(m3u8url, m3u8file)
  File "d:\ProgramData\Anaconda3\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "d:\ProgramData\Anaconda3\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "d:\ProgramData\Anaconda3\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "d:\ProgramData\Anaconda3\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "d:\ProgramData\Anaconda3\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "d:\ProgramData\Anaconda3\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "d:\ProgramData\Anaconda3\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by hcjohn463** [comment]
網站代碼被更新了 
2021/5/27 已更新 main.py
謝謝您提出問題

**Comment by Howard2306** [comment]
> 网站代码被更新了
> 2021/5/27 已更新 main.py
> 谢谢您提出问题

您好，好奇網站代碼被更新是什麼意思
程式不是一樣照抓就行了嗎？

**Comment by Riroaki** [comment]
> > 网站代码被更新了
> > 2021/5/27 已更新 main.py
> > 谢谢您提出问题
> 
> 您好，好奇網站代碼被更新是什麼意思
> 程式不是一樣照抓就行了嗎？

网站做了反爬虫处理，对疑似机器的请求返回403forbidden

**Comment by yinhaoooo** [comment]
谢谢

**Comment by hcjohn463** [comment]
已更新重新上傳!
如果覺得好用 再麻煩你們幫忙按個星星
這樣搜尋才能到比較上面
有問題提出我都會繼續更新
大家一起讓世界更美好
謝謝你們~
