### ISSUE TITLE
Failed after Chrome updated to 116

### ISSUE THREAD

**Issue by rurumi0318** [hcjohn463/JableTVDownload#121]
Not sure if this issue is related to the one on stackoverflow
https://stackoverflow.com/questions/76913935/selenium-common-exceptions-sessionnotcreatedexception-this-version-of-chromedri

[0824/001451.371:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
Traceback (most recent call last):
  File "E:\H\JableTVDownload\main.py", line 26, in <module>
    download(url)
  File "E:\H\JableTVDownload\download.py", line 46, in download
    dr = webdriver.Chrome(options=options)
  File "E:\H\JableTVDownload\jable\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 84, in __init__
    super().__init__(
  File "E:\H\JableTVDownload\jable\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in __init__
    super().__init__(
  File "E:\H\JableTVDownload\jable\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "E:\H\JableTVDownload\jable\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "E:\H\JableTVDownload\jable\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "E:\H\JableTVDownload\jable\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.111 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
        GetHandleVerifier [0x0105A813+48355]
        (No symbol) [0x00FEC4B1]
        (No symbol) [0x00EF5358]
        (No symbol) [0x00F161AC]
        (No symbol) [0x00F11EF3]
        (No symbol) [0x00F10579]
        (No symbol) [0x00F40C55]
        (No symbol) [0x00F4093C]
        (No symbol) [0x00F3A536]
        (No symbol) [0x00F182DC]
        (No symbol) [0x00F193DD]
        GetHandleVerifier [0x012BAABD+2539405]
        GetHandleVerifier [0x012FA78F+2800735]
        GetHandleVerifier [0x012F456C+2775612]
        GetHandleVerifier [0x010E51E0+616112]
        (No symbol) [0x00FF5F8C]
        (No symbol) [0x00FF2328]
        (No symbol) [0x00FF240B]
        (No symbol) [0x00FE4FF7]
        BaseThreadInitThunk [0x76F77D59+25]
        RtlInitializeExceptionChain [0x7760B79B+107]
        RtlClearBits [0x7760B71F+191]

**Comment by anasiandeude** [comment]
go to https://googlechromelabs.github.io/chrome-for-testing/#stable download the matching version of the chromedriver and replace the one in the jable downloader folder then you're good to go

**Comment by rurumi0318** [comment]
> 

It's fixed after applied the new driver.
