### ISSUE TITLE
出现chrome浏览器不支持问题

### ISSUE THREAD

**Issue by baidongcaas** [hcjohn463/JableTVDownload#128]
This version of ChromeDriver only supports Chrome version 114

**Comment by ShakesBill** [comment]
同样的问题，下载114版本的chrome或者等代码更新

**Comment by ShakesBill** [comment]
错误提示里有写当前版本，下载对应版本的chromedriver放到jabletv的文件夹里替换旧版，https://googlechromelabs.github.io/chrome-for-testing/#stable

**Comment by baidongcaas** [comment]
> 错误提示里有写当前版本，下载对应版本的chromedriver放到jabletv的文件夹里替换旧版，https://googlechromelabs.github.io/chrome-for-testing/#stable

thank you, i solved this by your method.

**Comment by kptung** [comment]
目前114版本已無法使用，要用stable版本117

**Comment by mikechan0731** [comment]
剛剛測試，要更新到 120 以上才能抓

**Comment by baidongcaas** [comment]
非常感谢，我已经了解了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Mike Chan ***@***.***&gt;
发送时间: 2023年12月9日 12:20
收件人: hcjohn463/JableTVDownload ***@***.***&gt;
抄送: baidong_tum ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [hcjohn463/JableTVDownload] 出现chrome浏览器不支持问题 (Issue #128)





 
剛剛測試，要更新到 120 以上才能抓

**Comment by kptung** [comment]
stable版本可以用約2個月，記得2個月更換一次就可

**Comment by baidongcaas** [comment]
行，非常感谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: kptung ***@***.***&gt;
发送时间: 2023年12月9日 16:49
收件人: hcjohn463/JableTVDownload ***@***.***&gt;
抄送: baidong_tum ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [hcjohn463/JableTVDownload] 出现chrome浏览器不支持问题 (Issue #128)





 
stable版本可以用約2個月，記得2個月更換一次就可

**Comment by 8680** [comment]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Tools\JableTVDownload-main\main.py", line 26, in <module>
    download(url)
  File "F:\Tools\JableTVDownload-main\download.py", line 48, in download
    dr = webdriver.Chrome(options=options)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Tools\JableTVDownload-main\jable\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "F:\Tools\JableTVDownload-main\jable\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 50, in __init__
    if finder.get_browser_path():
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Tools\JableTVDownload-main\jable\Lib\site-packages\selenium\webdriver\common\driver_finder.py", line 47, in get_browser_path
    return self._binary_paths()["browser_path"]
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\Tools\JableTVDownload-main\jable\Lib\site-packages\selenium\webdriver\common\driver_finder.py", line 78, in _binary_paths
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

ChromeDriver stable 版本:
128.0.6613.120
有根大的知道怎么解决吗

**Comment by 8680** [comment]
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\selenium\webdriver\common\driver_finder.py", line 75, in _binary_paths
    raise ValueError(f'The browser path is not a valid file: {output["browser_path"]}')
ValueError: The browser path is not a valid file:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Tools\JableTVDownload-main\main.py", line 26, in <module>
    download(url)
  File "F:\Tools\JableTVDownload-main\download.py", line 48, in download
    dr = webdriver.Chrome(options=options)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Python312\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 50, in __init__
    if finder.get_browser_path():
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\selenium\webdriver\common\driver_finder.py", line 47, in get_browser_path
    return self._binary_paths()["browser_path"]
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\selenium\webdriver\common\driver_finder.py", line 78, in _binary_paths
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
