### ISSUE TITLE
牛逼！但是如何加入翻墙的模块？

### ISSUE THREAD

**Issue by Dominic-ZZ** [hcjohn463/JableTVDownload#2]
rt

**Comment by Dominic-ZZ** [comment]
我试着加入代理翻墙的模块，但是遇到了各种问题。
最后通过直接读取u3m8文件的url，跳过request请求jable网页的部分，解决。

**Comment by hcjohn463** [comment]
恭喜哦!

**Comment by code33** [comment]
所在局域网内开启运行http代理 然后把这段代码在复制,用以运行main.py
```
export http_proxy='http://127.0.0.1:4780'&& export https_proxy='http://127.0.0.1:4780' && export proxy='http://127.0.0.1:4780' &&  python main.py
```

**Comment by BarryLiu97** [comment]
请问该问题如何解决
```
Traceback (most recent call last):
  File "D:\ProgramData\Miniconda3\envs\jable\lib\site-packages\urllib3\connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "D:\ProgramData\Miniconda3\envs\jable\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "D:\ProgramData\Miniconda3\envs\jable\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Miniconda3\envs\jable\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "D:\ProgramData\Miniconda3\envs\jable\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "D:\ProgramData\Miniconda3\envs\jable\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "D:\ProgramData\Miniconda3\envs\jable\lib\site-packages\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "D:\ProgramData\Miniconda3\envs\jable\lib\site-packages\urllib3\connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000019B09E71048>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Miniconda3\envs\jable\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\ProgramData\Miniconda3\envs\jable\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "D:\ProgramData\Miniconda3\envs\jable\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='jable.tv', port=443): Max retries exceeded with url: /videos/ipx-647/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B09E71048>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正 确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 47, in <module>
    htmlfile = requests.get(url)
  File "D:\ProgramData\Miniconda3\envs\jable\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "D:\ProgramData\Miniconda3\envs\jable\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\ProgramData\Miniconda3\envs\jable\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\ProgramData\Miniconda3\envs\jable\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\ProgramData\Miniconda3\envs\jable\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='jable.tv', port=443): Max retries exceeded with url: /videos/ipx-647/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019B09E71048>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时 间后没 有正确答复或连接的主机没有反应，连接尝试失败。'))
```

**Comment by hcjohn463** [comment]
已更新重新上傳!
如果覺得好用 再麻煩你們幫忙按個星星
這樣搜尋才能到比較上面
有問題提出我都會繼續更新
大家一起讓世界更美好
謝謝你們~

**Comment by qninth** [comment]
1. 修改 main.py 中的 cloudscraper.create_scraper().get 函数参数，参考 https://mlog.club/article/5008181
2. 修改 crawl.py 中的 request.get 函数参数，参考 https://zhuanlan.zhihu.com/p/79466893

**Comment by 2niuhe** [comment]
@Dominic-ZZ  

添加代理可以看这边实现，我基于这个项目做了一些改进

https://github.com/2niuhe/jable_downloader/blob/3e237e92e05c3b7849ee05c27042603c810d16d0/utils.py#L37
