### ISSUE TITLE
check_hostname requires server_hostname

### ISSUE THREAD

**Issue by WhiteGho** [hcjohn463/JableTVDownload#25]
Traceback (most recent call last):
  File "main.py", line 47, in <module>
    htmlfile = requests.get(url)
  File "C:\Users\kame9\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\kame9\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\kame9\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\kame9\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\kame9\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\kame9\AppData\Local\Programs\Python\Python35-32\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\kame9\AppData\Local\Programs\Python\Python35-32\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\kame9\AppData\Local\Programs\Python\Python35-32\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\kame9\AppData\Local\Programs\Python\Python35-32\lib\site-packages\urllib3\connection.py", line 506, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "C:\Users\kame9\AppData\Local\Programs\Python\Python35-32\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\kame9\AppData\Local\Programs\Python\Python35-32\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\kame9\AppData\Local\Programs\Python\Python35-32\lib\ssl.py", line 377, in wrap_socket
    _context=self)
  File "C:\Users\kame9\AppData\Local\Programs\Python\Python35-32\lib\ssl.py", line 710, in __init__
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

**Comment by hcjohn463** [comment]
https://stackoverflow.com/questions/66642705/why-requests-raise-this-exception-check-hostname-requires-server-hostname
