### ISSUE TITLE
網頁更新!?

### ISSUE THREAD

**Issue by sssrelax** [hcjohn463/JableTVDownload#30]
網頁好像更新了......>.<"
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    m3u8url = result[0]
TypeError: 'NoneType' object is not subscriptable
(~~感謝作者大~~)

**Comment by Bjsef** [comment]
我也是一样的问题

**Comment by hcjohn463** [comment]
已更新 謝謝提出問題!

**Comment by sssrelax** [comment]
感謝大大的回應，更新後，出現以下訊息
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    m3u8url = result[0]
TypeError: 'NoneType' object is not subscriptable

還是非常感激作者大~~~

**Comment by hcjohn463** [comment]
> 感謝大大的回應，更新後，出現以下訊息
> Traceback (most recent call last):
> File "main.py", line 43, in
> m3u8url = result[0]
> TypeError: 'NoneType' object is not subscriptable
> 
> 還是非常感激作者大~~~

還是不行嗎..
我自己測了可以

**Comment by sherry218** [comment]
> > 感謝大大的回應，更新後，出現以下訊息
> > Traceback (most recent call last):
> > File "main.py", line 43, in
> > m3u8url = result[0]
> > TypeError: 'NoneType' object is not subscriptable
> > 還是非常感激作者大~~~
> 
> 還是不行嗎..
> 我自己測了可以

問題是出在requests
requests.get 的時候爬取不了網址
![image](https://user-images.githubusercontent.com/48175785/130748114-9970a70a-2fe2-447f-a83b-e439e6b1488c.png)

**Comment by hcjohn463** [comment]
> 
> 問題是出在requests
> requests.get 的時候爬取不了網址
> ![image](https://user-images.githubusercontent.com/48175785/130748114-9970a70a-2fe2-447f-a83b-e439e6b1488c.png)

你的多加headers也不行嗎..
![擷取](https://user-images.githubusercontent.com/45897386/130748834-b72389b1-049b-404d-b858-4e489c8cb6f4.PNG)

**Comment by sherry218** [comment]
是 我本來就是用有header的版本

**Comment by sherry218** [comment]
上面的人如果有急切需要的話 可以改成手動m3u8網址跳過requests部分

![image](https://user-images.githubusercontent.com/48175785/130750484-0c6a3680-c393-4796-80b5-26769d4045ca.png)

**Comment by Bjsef** [comment]
感谢各位的帮助，谢谢！！

**Comment by hcjohn463** [comment]
反反爬蟲已更新
如果有問題歡迎提出 謝謝你們~

**Comment by mikechan0731** [comment]
感謝作者

但是還是卡在

`result = re.search("https://.+m3u8", htmlfile.text)`

None

**Comment by hcjohn463** [comment]
> 感謝作者
> 
> 但是還是卡在
> 
> `result = re.search("https://.+m3u8", htmlfile.text)`
> 
> None

連改user agent都沒辦法嗎..
我再想想看是甚麼原因
謝謝您

**Comment by sherry218** [comment]
要不要試試看用selenium去爬蟲

**Comment by hcjohn463** [comment]
> 要不要試試看用selenium去爬蟲

selenium拿來動態操作網頁比較適合
如果只是要拿一個m3u8 url 
我想應該會有比較簡單的方法

**Comment by PyAver** [comment]
我也是卡住，看了一下是被 Cloudflare 擋住

**Comment by hcjohn463** [comment]
> 我也是卡住，看了一下是被 Cloudflare 擋住

謝謝你發現這個問題 !!
代碼更新過了 再麻煩試試看能不能跑

**Comment by PyAver** [comment]
> 謝謝您發現這個問題 !!
> 代碼更新過了 再麻煩您試試看能不能跑

我測試是不行的，不過改成下面這就成功 work

`htmlfile = cloudscraper.create_scraper(browser='firefox', delay=10).get(url)`

不知道其他人的情況是不是也是這問題

**Comment by Athena360** [comment]
我剛下載了最新版本,發現在windows環境下是沒有問題的。但是在linux環境下就出現typeerror:nonetype object is not found.的問題

**Comment by hcjohn463** [comment]
已更新重新上傳!
如果覺得好用 再麻煩你們幫忙按個星星
這樣搜尋才能到比較上面
有問題提出我都會繼續更新
大家一起讓世界更美好
謝謝你們~

**Comment by le0liu** [comment]
linux 还有救吗?获取m3u8太不方便了.

**Comment by arthurzllu** [comment]
我按照這篇 (https://blog.csdn.net/Skillfully/article/details/115165480) 的做法解決Ubuntu上不能抓到m3u8的問題。我做的事情是：
先執行 pip3 uninstall pycryptodome Crypto；接著，很重要，一定要先 pip3 install pycryptodome 而後 pip3 install Crypto。供各位參考。

**Comment by le0liu** [comment]
感谢 已经解决了 最后我把cloudscraper.create_scraper(browser='firefox', delay=10).get(url)改成requests.get(url,headers= headers)  不然会报错RuntimeError: Sorry "firefox" browser was not found with a platform of "ios"

**Comment by PyAver** [comment]
> 感谢 已经解决了 最后我把cloudscraper.create_scraper(browser='firefox', delay=10).get(url)改成requests.get(url,headers= headers) 不然会报错RuntimeError: Sorry "firefox" browser was not found with a platform of "ios"

platform 限定成某個平台也可以解決

```
    htmlfile = cloudscraper.create_scraper(
            browser={
                'browser': 'firefox',
                'platform': 'windows',
                'mobile': False
            }, 
            delay=10
        ).get(url)
```
