### ISSUE TITLE
请问直连就是等一会连接尝试失败。挂梯子就是(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))怎么解决

### ISSUE THREAD

**Issue by superkca** [hcjohn463/JableTVDownload#67]
直连
Traceback (most recent call last):
  File "H:\python\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "H:\python\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "H:\python\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "H:\python\lib\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "H:\python\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000026562257970>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

挂梯子
Traceback (most recent call last):
  File "C:\Users\10146\Downloads\JableTVDownload-main\JableTVDownload-main\main.py", line 49, in <module>
    htmlfile =cloudscraper.create_scraper(delay=8).get(url)
  File "H:\python\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "H:\python\lib\site-packages\cloudscraper\__init__.py", line 263, in request
    self.perform_request(method, url, *args, **kwargs)
  File "H:\python\lib\site-packages\cloudscraper\__init__.py", line 182, in perform_request
    return super(CloudScraper, self).request(method, url, *args, **kwargs)
  File "H:\python\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "H:\python\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "H:\python\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='jable.tv', port=443): Max retries exceeded with url: /videos/mifd-117/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

**Comment by mrZhong887** [comment]
同样问题。。。但是在公司网络下就能够正常使用。

**Comment by superkca** [comment]
> 



> 同样问题。。。但是在公司网络下就能够正常使用。

公司网络下片片不太好吧哈哈哈，可别被发现了

**Comment by hansen0086** [comment]
我在家也有同样的问题，通过重装urllib然后改写get最后能用了。
用下面这行重装urllib：
pip install urllib3==1.25.11
装好了这个之后能debug会发现ssl问题解决了，但是访问网站出现403错误，导致m3u8链接为空，需要改header，这个地方我重写了get之后就能用了

**Comment by Nanojiaximoduo** [comment]
和上面老哥一样装个旧版urllib换个浏览器就好使

**Comment by i990099** [comment]
> 我在家也有同样的问题，通过重装urllib然后改写get最后能用了。 用下面这行重装urllib： pip install urllib3==1.25.11 装好了这个之后能debug会发现ssl问题解决了，但是访问网站出现403错误，导致m3u8链接为空，需要改header，这个地方我重写了get之后就能用了

方便把改写的代码贴出来吗
