### ISSUE TITLE
SyntaxError: invalid hexadecimal literal

### ISSUE THREAD

**Issue by tianrongzhang1** [hcjohn463/JableTVDownload#75]
Traceback (most recent call last):
  File "C:\Develop\Projects\GitHubProjects\JableTVDownload\main.py", line 13, in <module>
    from Crypto.Cipher import AES
  File "C:\Develop\Projects\GitHubProjects\JableTVDownload\jable\lib\site-packages\Crypto\Cipher\__init__.py", line 82, in <module>
    from Crypto.Cipher._mode_ctr import _create_ctr_cipher
  File "C:\Develop\Projects\GitHubProjects\JableTVDownload\jable\lib\site-packages\Crypto\Cipher\_mode_ctr.py", line 35, in <module>
    from Crypto.Util.number import long_to_bytes
  File "C:\Develop\Projects\GitHubProjects\JableTVDownload\jable\lib\site-packages\Crypto\Util\number.py", line 398
    s = pack('>I', n & 0xffffffffL) + s
                                ^
SyntaxError: invalid hexadecimal literal

请问这里如何解决？

**Comment by nelsonkti** [comment]
pip uninstall crypto
pip uninstall pycryptodome
pip install pycryptodome

**Comment by tianrongzhang1** [comment]
> pip uninstall crypto pip uninstall pycryptodome pip install pycryptodome

已解决，谢谢老哥
