### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by Dissyu** [hcjohn463/JableTVDownload#86]
正在下載影片: https://jable.tv/videos/salo-017/
Traceback (most recent call last):
  File "I:\JableTVDownload-allow-multilple-download-from-model-page\main.py", line 35, in <module>
    download(url)
  File "I:\JableTVDownload-allow-multilple-download-from-model-page\download.py", line 39, in download
    urllib.request.urlretrieve(m3u8url, m3u8file)
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
-------------------------------------------------------------------------------------------------------------------------------------------

請問有辦法解決嗎~

**Comment by IntangibleW** [comment]
> add -headers "referer: http://jable.tv"

still don't understand

**Comment by Calvin-830** [comment]
opener = urllib.request.build_opener()
opener.addheaders = [('User-Agent','Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36'), ('Referer', 'https://jable.tv')]
urllib.request.install_opener(opener)
urllib.request.urlretrieve(m3u8url, m3u8file)

config.py add 'referer' : 'https://jable.tv'

**Comment by shiverman** [comment]
> main.py modify opener = urllib.request.build_opener() opener.addheaders = [('User-Agent','Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36'), ('Referer', 'https://jable.tv')] urllib.request.install_opener(opener) urllib.request.urlretrieve(m3u8url, m3u8file)
> 
> config.py add 'referer' : 'https://jable.tv'

it works.

**Comment by Dissyu** [comment]
> 

still dont understand. how make it work ?

**Comment by Calvin-830** [comment]
Please checkout https://github.com/Calvin-830/JableTVDownload

**Comment by Dissyu** [comment]
I think I done what you say. but I get new issue.
Could you try download this video? 
https://jable.tv/videos/hodv-21402/

I got the "ValueError: Incorrect AES key length."
Traceback (most recent call last):
  File "I:\test\main.py", line 98, in <module>
    ci = AES.new(contentKey, AES.MODE_CBC, vt)  # 建構解碼器
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\site-packages\Crypto\Cipher\AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\site-packages\Crypto\Cipher\__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\site-packages\Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\site-packages\Crypto\Cipher\AES.py", line 93, in _create_base_cipher
    raise ValueError("Incorrect AES key length (%d bytes)" % len(key))
ValueError: Incorrect AES key length (2334 bytes)

**Comment by Dissyu** [comment]
Hello sir . new issue
could you try download belowe video?
https://jable.tv/videos/062614-833/

Traceback (most recent call last):
  File "I:\original_test\main.py", line 65, in <module>
    urllib.request.urlretrieve(m3u8url, m3u8file)
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 428:

**Comment by Dissyu** [comment]
hello sir . i got new issue 
could you try download belowe video link?
https://jable.tv/videos/docp-237/



Traceback (most recent call last):
  File "I:\JableTVDownload-allow-multilple-download-from-model-page\main.py", line 39, in <module>
    download(url)
  File "I:\JableTVDownload-allow-multilple-download-from-model-page\download.py", line 42, in download
    urllib.request.urlretrieve(m3u8url, m3u8file)
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\Bcy\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 428:
