### ISSUE TITLE
大佬们 有没有支持群辉nas部署下载的教程

### ISSUE THREAD

**Issue by shiyuanGame** [hcjohn463/JableTVDownload#87]
大佬们 有没有支持群辉nas部署下载的教程  也刚玩nas 玩的不是很转  谢谢各位大佬 好人一生平安

**Comment by shiyuanGame** [comment]
兄弟们 我已经搞明白了
参考的
https://www.bilibili.com/video/av414314529/?vd_source=8a7a2007a36d938a310e6e2a676e8eb7

**Comment by shiyuanGame** [comment]
![image](https://user-images.githubusercontent.com/80084199/209470155-55794c04-c08e-4df7-aa22-d71b5a3b4ced.png)
真鸡儿兴奋

**Comment by shiyuanGame** [comment]
遇到什么错就解决 百度

**Comment by shiyuanGame** [comment]
我断断续续折腾了一个月 激动

**Comment by joywqy** [comment]
> 兄弟们 我已经搞明白了 参考的 https://www.bilibili.com/video/av414314529/?vd_source=8a7a2007a36d938a310e6e2a676e8eb7

视频怎么不见了

**Comment by shiyuanGame** [comment]
> 
目前不支持linux版本了 只有docker版本  这是我编译的版本
https://registry.hub.docker.com/r/shiyuangame/jabletv/
我修改了Road-tech大佬的源码 编译了docker版本 使用方式在说明
https://github.com/shiyuanGame/Docker_JableTVDownload

**Comment by shiyuanGame** [comment]
> > 兄弟们 我已经搞明白了 参考的 https://www.bilibili.com/video/av414314529/?vd_source=8a7a2007a36d938a310e6e2a676e8eb7
> 
> 视频怎么不见了

我写在csdn上一版 ，这个前段时间是能用的 现在也不好用了
https://blog.csdn.net/qq_36848370/article/details/128456768

**Comment by joywqy** [comment]
> > 
> 
> 目前不支持linux版本了 只有docker版本 这是我编译的版本 https://registry.hub.docker.com/r/shiyuangame/jabletv/ 我修改了Road-tech大佬的源码 编译了docker版本 使用方式在说明 https://github.com/shiyuanGame/Docker_JableTVDownload

运行这个命令 后 docker run --rm  -v /Your/download/dir:/data -e URL="https://jable.tv/videos/ssis-XXX/" shiyuangame/jabletv，也成功下载了，我该到哪里去取下载的文件啊，谢谢

**Comment by shiyuanGame** [comment]
> > > 
> 
> > 
> 
> > 目前不支持linux版本了 只有docker版本 这是我编译的版本 https://registry.hub.docker.com/r/shiyuangame/jabletv/ 我修改了Road-tech大佬的源码 编译了docker版本 使用方式在说明 https://github.com/shiyuanGame/Docker_JableTVDownload
> 
> 
> 
> 运行这个命令 后 docker run --rm  -v /Your/download/dir:/data -e URL="https://jable.tv/videos/ssis-XXX/" shiyuangame/jabletv，也成功下载了，我该到哪里去取下载的文件啊，谢谢

如果你不修改路径的话就在你的主目录 Your/download/dir 这个是diy的路径支持修改的

**Comment by joywqy** [comment]
> > > >
> > 
> > 
> > > 
> > 
> > 
> > > 目前不支持linux版本了 只有docker版本 这是我编译的版本 https://registry.hub.docker.com/r/shiyuangame/jabletv/ 我修改了Road-tech大佬的源码 编译了docker版本 使用方式在说明 https://github.com/shiyuanGame/Docker_JableTVDownload
> > 
> > 
> > 运行这个命令 后 docker run --rm  -v /Your/download/dir:/data -e URL="https://jable.tv/videos/ssis-XXX/" shiyuangame/jabletv，也成功下载了，我该到哪里去取下载的文件啊，谢谢
> 
> 如果你不修改路径的话就在你的主目录 Your/download/dir 这个是diy的路径支持修改的

我是windows安装了Docker Desktop，我应该去windows找还是去docker镜像找？

**Comment by shiyuanGame** [comment]
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 目前不支持linux版本了 只有docker版本 这是我编译的版本 https://registry.hub.docker.com/r/shiyuangame/jabletv/ 我修改了Road-tech大佬的源码 编译了docker版本 使用方式在说明 https://github.com/shiyuanGame/Docker_JableTVDownload
> 
> > > 
> 
> > > 
> 
> > > 运行这个命令 后 docker run --rm  -v /Your/download/dir:/data -e URL="https://jable.tv/videos/ssis-XXX/" shiyuangame/jabletv，也成功下载了，我该到哪里去取下载的文件啊，谢谢
> 
> > 
> 
> > 如果你不修改路径的话就在你的主目录 Your/download/dir 这个是diy的路径支持修改的
> 
> 
> 
> 我是windows安装了Docker Desktop，我应该去windows找还是去docker镜像找？

你熟悉linux命令吗 cd ls看看  如果是windows环境直接从那个github的项目跑python能跑通我测试过。不用再用docker环境了

**Comment by shiyuanGame** [comment]
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 目前不支持linux版本了 只有docker版本 这是我编译的版本 https://registry.hub.docker.com/r/shiyuangame/jabletv/ 我修改了Road-tech大佬的源码 编译了docker版本 使用方式在说明 https://github.com/shiyuanGame/Docker_JableTVDownload
> 
> > > 
> 
> > > 
> 
> > > 运行这个命令 后 docker run --rm  -v /Your/download/dir:/data -e URL="https://jable.tv/videos/ssis-XXX/" shiyuangame/jabletv，也成功下载了，我该到哪里去取下载的文件啊，谢谢
> 
> > 
> 
> > 如果你不修改路径的话就在你的主目录 Your/download/dir 这个是diy的路径支持修改的
> 
> 
> 
> 我是windows安装了Docker Desktop，我应该去windows找还是去docker镜像找？

https://github.com/shiyuanGame/JableTVDownload 这个试试看 我在vscode测试过 pc环境没问题 直接运行download.py 传一个url进去

**Comment by joywqy** [comment]
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 目前不支持linux版本了 只有docker版本 这是我编译的版本 https://registry.hub.docker.com/r/shiyuangame/jabletv/ 我修改了Road-tech大佬的源码 编译了docker版本 使用方式在说明 https://github.com/shiyuanGame/Docker_JableTVDownload
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 运行这个命令 后 docker run --rm  -v /Your/download/dir:/data -e URL="https://jable.tv/videos/ssis-XXX/" shiyuangame/jabletv，也成功下载了，我该到哪里去取下载的文件啊，谢谢
> > 
> > 
> > > 
> > 
> > 
> > > 如果你不修改路径的话就在你的主目录 Your/download/dir 这个是diy的路径支持修改的
> > 
> > 
> > 我是windows安装了Docker Desktop，我应该去windows找还是去docker镜像找？
> 
> https://github.com/shiyuanGame/JableTVDownload 这个试试看 我在vscode测试过 pc环境没问题 直接运行download.py 传一个url进去

后面还是用docker里的下载成功了，使用https://github.com/shiyuanGame/JableTVDownload 还是会报错
`正在下載影片: https://jable.tv/videos/081319-002/
C:\Users\wqy\Desktop\JableTVDownload-main\download.py:35: DeprecationWarning: use options instead of chrome_options
  dr = webdriver.Chrome(chrome_options=options)

DevTools listening on ws://127.0.0.1:51025/devtools/browser/dbd63ef7-d044-41e6-b10e-f15149e07c37
[0526/101428.012:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[0526/101433.276:INFO:CONSOLE(470)] "An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.", source: https://imasdk.googleapis.com/js/sdkloader/ima3.js (470)
[0526/101433.293:INFO:CONSOLE(0)] "An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.", source: about:srcdoc (0)
[0526/101434.916:INFO:CONSOLE(0)] "Uncaught (in promise) undefined", source: https://jable.tv/videos/081319-002/ (0)
dr.title:081319-002 極品熟女北條麻妃滿足男性的任何願望 - Jable.TV | 免費高清AV在線看 | J片 AV看到飽
tempchangeName:081319-002 極品熟女北條麻妃滿足男性的任何願望
result: <re.Match object; span=(52086, 52181), match='https://bogoo-alive.mushroomtrack.com/hls/jI-0EUJ>
m3u8url: https://bogoo-alive.mushroomtrack.com/hls/jI-0EUJx5ivXKFEwjY-3Lw/1685077856/2000/2546/2546.m3u8
Traceback (most recent call last):
  File "C:\Users\wqy\Desktop\JableTVDownload-main\download.py", line 124, in <module>
    download("https://jable.tv/videos/081319-002/") #   测试下载
  File "C:\Users\wqy\Desktop\JableTVDownload-main\download.py", line 76, in download
    m3u8obj = m3u8.load(m3u8file)
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\m3u8\__init__.py", line 48, in load
    content, base_uri = http_client.download(uri, timeout, headers, verify_ssl)
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\m3u8\httpclient.py", line 17, in download
    resource = opener.open(uri, timeout=timeout)
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\urllib\request.py", line 539, in _open
    return self._call_chain(self.handle_open, 'unknown',
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\urllib\request.py", line 1417, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: c>`

**Comment by shiyuanGame** [comment]
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > 目前不支持linux版本了 只有docker版本 这是我编译的版本 https://registry.hub.docker.com/r/shiyuangame/jabletv/ 我修改了Road-tech大佬的源码 编译了docker版本 使用方式在说明 https://github.com/shiyuanGame/Docker_JableTVDownload
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 运行这个命令 后 docker run --rm  -v /Your/download/dir:/data -e URL="https://jable.tv/videos/ssis-XXX/" shiyuangame/jabletv，也成功下载了，我该到哪里去取下载的文件啊，谢谢
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 如果你不修改路径的话就在你的主目录 Your/download/dir 这个是diy的路径支持修改的
> 
> > > 
> 
> > > 
> 
> > > 我是windows安装了Docker Desktop，我应该去windows找还是去docker镜像找？
> 
> > 
> 
> > https://github.com/shiyuanGame/JableTVDownload 这个试试看 我在vscode测试过 pc环境没问题 直接运行download.py 传一个url进去
> 
> 
> 
> 后面还是用docker里的下载成功了，使用https://github.com/shiyuanGame/JableTVDownload 还是会报错
> 
> `
> 
> 正在下載影片: https://jable.tv/videos/081319-002/
> 
> C:\Users\wqy\Desktop\JableTVDownload-main\download.py:35: DeprecationWarning: use options instead of chrome_options
> 
>   dr = webdriver.Chrome(chrome_options=options)
> 
> 
> 
> DevTools listening on ws://127.0.0.1:51025/devtools/browser/dbd63ef7-d044-41e6-b10e-f15149e07c37
> 
> [0526/101428.012:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
> 
> [0526/101433.276:INFO:CONSOLE(470)] "An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.", source: https://imasdk.googleapis.com/js/sdkloader/ima3.js (470)
> 
> [0526/101433.293:INFO:CONSOLE(0)] "An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.", source: about:srcdoc (0)
> 
> [0526/101434.916:INFO:CONSOLE(0)] "Uncaught (in promise) undefined", source: https://jable.tv/videos/081319-002/ (0)
> 
> dr.title:081319-002 極品熟女北條麻妃滿足男性的任何願望 - Jable.TV | 免費高清AV在線看 | J片 AV看到飽
> 
> tempchangeName:081319-002 極品熟女北條麻妃滿足男性的任何願望
> 
> result: <re.Match object; span=(52086, 52181), match='https://bogoo-alive.mushroomtrack.com/hls/jI-0EUJ>
> 
> m3u8url: https://bogoo-alive.mushroomtrack.com/hls/jI-0EUJx5ivXKFEwjY-3Lw/1685077856/2000/2546/2546.m3u8
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\wqy\Desktop\JableTVDownload-main\download.py", line 124, in <module>
> 
>     download("https://jable.tv/videos/081319-002/") #   测试下载
> 
>   File "C:\Users\wqy\Desktop\JableTVDownload-main\download.py", line 76, in download
> 
>     m3u8obj = m3u8.load(m3u8file)
> 
>   File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\m3u8\__init__.py", line 48, in load
> 
>     content, base_uri = http_client.download(uri, timeout, headers, verify_ssl)
> 
>   File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\site-packages\m3u8\httpclient.py", line 17, in download
> 
>     resource = opener.open(uri, timeout=timeout)
> 
>   File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\urllib\request.py", line 517, in open
> 
>     response = self._open(req, data)
> 
>   File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\urllib\request.py", line 539, in _open
> 
>     return self._call_chain(self.handle_open, 'unknown',
> 
>   File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\urllib\request.py", line 494, in _call_chain
> 
>     result = func(*args)
> 
>   File "C:\Users\wqy\AppData\Local\Programs\Python\Python39-32\lib\urllib\request.py", line 1417, in unknown_open
> 
>     raise URLError('unknown url type: %s' % type)
> 
> urllib.error.URLError: <urlopen error unknown url type: c>
> 
> `
> 
> 

看文档 配置环境
