### ISSUE TITLE
 dr = webdriver.Chrome(chrome_options=options)  error  是少安裝了什麽嗎?

### ISSUE THREAD

**Issue by laochankao** [hcjohn463/JableTVDownload#97]
DevTools listening on ws://127.0.0.1:2196/devtools/browser/49ed67fd-e497-44e4-9c46-bd33d9c84e11
[0422/002340.950:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
Traceback (most recent call last):
  File "C:\Users\Ball\Desktop\JableTVDownload-main\main.py", line 26, in <module>
    download(url)
  File "C:\Users\Ball\Desktop\JableTVDownload-main\download.py", line 46, in download
    dr = webdriver.Chrome(chrome_options=options)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ball\Desktop\JableTVDownload-main\jable\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 84, in __init__
    super().__init__(
  File "C:\Users\Ball\Desktop\JableTVDownload-main\jable\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in __init__
    super().__init__(
  File "C:\Users\Ball\Desktop\JableTVDownload-main\jable\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Ball\Desktop\JableTVDownload-main\jable\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ball\Desktop\JableTVDownload-main\jable\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Ball\Desktop\JableTVDownload-main\jable\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 113
Current browser version is 112.0.5615.138 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:

**Comment by laochankao** [comment]
oh， my chrome version 113, i downgrate to 112 is ok .
